services:
  service:
    container_name: management
    build: ./
    env_file:
      - .env.dev
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - collector
      - redis

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:7.2.4
    ports:
      - "6379:6379"
    environment:
      REDIS_ARGS: "--requirepass redis redis-server --save 60 1 --loglevel warning"
    restart: unless-stopped

  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight:latest
    ports:
      - '5540:5540'

  collector:
    container_name: collector
    image: otel/opentelemetry-collector:0.88.0
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml
    command: [ "--config=/etc/otel-config.yaml" ]
    ports:
      - "4317:4317"

volumes:
  postgres:
  redis:
  redisinsight: