server:
  port: 8080

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: ${JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
    show-sql: ${JPA_PROPERTIES_SHOW_SQL}
  main:
    web-application-type: servlet
  cache:
    type: redis
    redis:
      time-to-live: ${CACHE_REDIS_TTL}
  data:
    redis:
      url: ${REDIS_URL}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      timeout: ${REDIS_TIMEOUT}

logging:
  level:
    com:
      mrtripop: ${LOGGING_LEVEL_COM_MRTRIPOP}
    org:
      hibernate: INFO

config:
  author:
    name: Tripop Torcheep
    email: tripop.chai12@gmail.com
  app:
    version: 1.0.0
    local-url: http://localhost:8080
    dev-url: http://dev-inventory.mrtripop-int.com
    stg-url: http://inventory.mrtripop-int.com
  spotify:
    url: https://spotify23.p.rapidapi.com


